// 侧边列表
export const GET_LIVE_LIST_EPIC = 'GET_LIVE_LIST_EPIC';

export const UPDATE_LIVE_LIST_REDUCER = 'UPDATE_LIVE_LIST_REDUCER';




// 正在热播
export const GET_HOT_NOW_LIVE_LIST_EPIC = 'GET_HOT_NOW_LIVE_LIST_EPIC';

export const UPDATE_HOT_NOW_LIVE_LIST_REDUCER = 'UPDATE_HOT_NOW_LIVE_LIST_REDUCER';



export const GET_INTERESTING_ANCHOR_EPIC = 'GET_INTERESTING_ANCHOR_EPIC';

export const UPDATE_INTERESTING_ANCHOR_REDUCER = 'UPDATE_INTERESTING_ANCHOR_REDUCER';

