export const GET_TOURNAMENT_PREVIEW = 'GET_TOURNAMENT_PREVIEW';

export const UPDATE_TOURNAMENT_PREVIEW = 'UPDATE_TOURNAMENT_PREVIEW';

// 当天赛事
export const GET_MATCH = 'GET_MATCH';

export const UPDATE_MATCH = 'UPDATE_MATCH';


