
// 登录
export const GET_LOGIN_EPIC = 'GET_LOGIN_EPIC';

export const UPDATE_LOGIN_REDUCER = 'UPDATE_LOGIN_REDUCER';

// 注册图形验证码
export const GET_RAND_CODE_EPIC = 'GET_RAND_CODE_EPIC';

export const UPDATE_RAND_CODE_REDUCER = 'UPDATE_RAND_CODE_REDUCER';

// 注册
export const GET_REGISTER_EPIC = 'GET_REGISTER_EPIC';

export const UPDATE_REGISTER_REDUCER = 'UPDATE_REGISTER_REDUCER';

// 找回/绑定手机验证码验证码
export const GET_CODE_EPIC = 'GET_CODE_EPIC';

export const UPDATE_CODE_REDUCER = 'UPDATE_CODE_REDUCER';

// 获取用户信息
export const GET_USER_INFO = 'GET_USER_INFO'; // 获取用户信息
export const UPDATE_USER_INFO_REDUCER = 'UPDATE_USER_INFO_REDUCER';

export const GET_USER_CARE_LIST = 'GET_USER_CARE_LIST'; // 获取用户关注列表
export const UPDATE_USER_CARE_LIST_REDUCER = 'UPDATE_USER_CARE_LIST_REDUCER';